# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://christopherneher.com
title: CHRISTOPHER NEHER
email: 
author:
description: > # "Write an awesome description for your new site here. 
  A birthday story
copyright: 'Copyright &copy; 2018 Giuliana Watson. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Click For Birthday
    url: http://citytastetours.com/

